[tox]
envlist = py313
isolated_build = True

[testenv]
deps =
  pytest>=7.0.0
  pytest-cov

commands = 
  pytest

[testenv:smoketests]
deps = 
    pytest>=7.0.0
    pytest-cov
commands = 
    pytest -k "smoke"
